server:
    port: 8443
    ssl:
        enabled: true
        key-store: classpath:statemachineserver.p12
        key-store-password: password
        key-store-type: pkcs12
        key-alias: statemachineserver
        key-password: password
